version: '3.9'
services:
  lss_portal_db:
    container_name: mysql-container-sample
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: defaultdb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      TZ: "Asia/Tokyo"
    volumes: 
      - ./volumes/mysqldata:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/migration:/docker-entrypoint-initdb.d
